CREATE TABLE `projects` (
	`id` text PRIMARY KEY NOT NULL,
	`name` text NOT NULL,
	`region` text NOT NULL,
	`location` text NOT NULL,
	`status` text NOT NULL,
	`risk` text NOT NULL,
	`health` real NOT NULL,
	`degrad` real NOT NULL,
	`diff` text NOT NULL,
	`ndvi` real,
	`rainfall` real NOT NULL,
	`moisture` real,
	`ph` real NOT NULL,
	`carbon_soil` real NOT NULL,
	`aridity` real NOT NULL,
	`lstemp` real,
	`area` text NOT NULL,
	`cost` text NOT NULL,
	`timeline` text NOT NULL,
	`water` text NOT NULL,
	`carbon` text NOT NULL,
	`terrain_bg` text NOT NULL,
	`terrain_stroke` text NOT NULL,
	`terrain_fill` text NOT NULL,
	`health_col` text NOT NULL,
	`phases` text NOT NULL,
	`species` text NOT NULL,
	`treatments` text NOT NULL,
	`recs` text NOT NULL,
	`current_step` integer NOT NULL,
	`aoi` text NOT NULL,
	`satellite` text,
	`drone_logs` text NOT NULL,
	`soil` text,
	`microbiome` text,
	`prescription` text,
	`kanban` text NOT NULL,
	`resources` text,
	`biomass` text NOT NULL,
	`dmrv` text NOT NULL,
	`carbon_sequestered_tons` real NOT NULL
);
