import { sqliteTable, text, real, integer } from "drizzle-orm/sqlite-core"
import type {
  Phase,
  Recommendation,
  AOI,
  SatelliteMetrics,
  DroneFlightLog,
  SoilComposition,
  Microbiome,
  KanbanTask,
  ResourceInventory,
  BiomassPoint,
  DMRVStep,
} from "@/data/projects"
import type { RehabilitationReport } from "@/data/rehabilitation-report"

export const projectsTable = sqliteTable("projects", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  region: text("region").notNull(),
  location: text("location").notNull(),
  status: text("status", { enum: ["planning", "active"] }).notNull(),
  risk: text("risk", { enum: ["SEVERE", "LOW"] }).notNull(),
  health: real("health").notNull(),
  degrad: real("degrad").notNull(),
  diff: text("diff", { enum: ["HIGH", "LOW"] }).notNull(),
  ndvi: real("ndvi"),
  rainfall: real("rainfall").notNull(),
  moisture: real("moisture"),
  ph: real("ph"),
  carbonSoil: real("carbon_soil"),
  aridity: real("aridity").notNull(),
  lstemp: real("lstemp"),
  area: text("area").notNull(),
  cost: text("cost").notNull(),
  timeline: text("timeline").notNull(),
  water: text("water").notNull(),
  carbon: text("carbon").notNull(),
  terrainBg: text("terrain_bg").notNull(),
  terrainStroke: text("terrain_stroke").notNull(),
  terrainFill: text("terrain_fill").notNull(),
  healthCol: text("health_col").notNull(),
  phases: text("phases", { mode: "json" }).notNull().$type<Phase[]>(),
  species: text("species", { mode: "json" }).notNull().$type<string[]>(),
  treatments: text("treatments", { mode: "json" }).notNull().$type<string[]>(),
  recs: text("recs", { mode: "json" }).notNull().$type<Recommendation[]>(),
  currentStep: integer("current_step").notNull(),
  aoi: text("aoi", { mode: "json" }).notNull().$type<AOI>(),
  satellite: text("satellite", { mode: "json" }).$type<SatelliteMetrics>(),
  droneLogs: text("drone_logs", { mode: "json" }).notNull().$type<DroneFlightLog[]>(),
  soil: text("soil", { mode: "json" }).$type<SoilComposition>(),
  microbiome: text("microbiome", { mode: "json" }).$type<Microbiome>(),
  rehabReport: text("rehab_report", { mode: "json" }).$type<RehabilitationReport>(),
  kanban: text("kanban", { mode: "json" }).notNull().$type<KanbanTask[]>(),
  resources: text("resources", { mode: "json" }).$type<ResourceInventory>(),
  biomass: text("biomass", { mode: "json" }).notNull().$type<BiomassPoint[]>(),
  dmrv: text("dmrv", { mode: "json" }).notNull().$type<DMRVStep[]>(),
  carbonSequesteredTons: real("carbon_sequestered_tons").notNull(),
})
