"use client"

import React from "react"

export const SignoffSection: React.FC = () => (
  <div className="rx-signoff">
    <p className="rx-section-intro" style={{ marginTop: 0 }}>
      This prescription is generated from satellite, soil, and field data on record for this
      parcel at the time of generation. It is a planning instrument, not a substitute for
      on-site verification by a qualified agronomist prior to execution.
    </p>

    <div className="rx-sig-row">
      <div>
        <div className="rx-sig-line" />
        <div className="rx-sig-caption">Prepared By — DROS AI Prescription Engine</div>
      </div>
      <div>
        <div className="rx-sig-line" />
        <div className="rx-sig-caption">Reviewed By — Site Agronomist</div>
      </div>
    </div>

    <div className="rx-disclaimer">
      This document was generated by an AI system from project telemetry and does not constitute
      a certified soil or agronomic survey. Dosages, costs, and timelines are estimates for
      planning purposes and should be confirmed against current supplier pricing and an on-site
      inspection before procurement or field execution begins.
    </div>
  </div>
)
